# Generated by Django 4.0.6 on 2022-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.AddField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
